### ISSUE TITLE
come avviare l'app

### ISSUE THREAD

**Issue by ghost** [EnricoTolomei/GTFS_RSM#4]
salve, non riesco a trovare il file exe per avviare il programma

**Comment by EnricoTolomei** [comment]
Ciao @bobbosit,
nalla schermata iniziale del repository, sulla parte destra dovresti trovare il link per l' ultima release [https://github.com/EnricoTolomei/GTFS_RSM/releases/tag/v_1.16](release)
arrivi in una schermata come questa
![Immagine](https://user-images.githubusercontent.com/48106183/105006890-8a9a4800-5a37-11eb-99b1-1cfd6bb085f5.png)
da dove puoi scaricare il file compresso **Programma_Monitoraggio_Bus.7z**, estrai l'archivio ed all'interno della cartella troverai il file **`Atac_Feed.exe`**.
Fammi sapere se incontri altre problematiche oppure se hai idee per estendere le funzionalità del programma

**Comment by EnricoTolomei** [comment]
Grazie della segnalazione,ho aggiornato la pagina iniziale riportando il link per il download dell'ultima versione


    Il lunedì 18 gennaio 2021, 22:52:12 CET, bobbosit ***@***.***> ha scritto:  
 
 


salve, non riesco a trovare il file exe per avviare il programma
