### ISSUE TITLE
Ridimensiona form

### ISSUE THREAD

**Issue by Levs75** [EnricoTolomei/GTFS_RSM#5]
Vorrei far presente il problema che riscontro sul mio PC nel ridimensionamento della schermata, che di fatto mi impedisce di utilizzare l'applicazione. Non riesco a vedere una parte della schermata, penso che il pulsante per avviare sia nascosto sulla destra.
![ingranditaestesa](https://user-images.githubusercontent.com/112714359/188183129-883ece05-cdfa-42ad-b7af-a9e1d08cd328.jpg)
![apertura](https://user-images.githubusercontent.com/112714359/188183133-580a55a1-b842-4bea-a13a-6f42e3fa1bf5.jpg)

**Comment by EnricoTolomei** [comment]
Grazie per la segnalazione, conto di risolvere a breve (e di non scatenare l'allineamento cosmico sfavorevole con questa mia dichiarazione)

In effetti il pulsante è sulla parte destra

**Comment by EnricoTolomei** [comment]
La versione 1.31 risolve il problema.
Verificato con una risoluzione video di 1280x1024 (se hai ancora problemi fammi sapere che risoluzione hai impostato)

**Comment by Levs75** [comment]
Confermo che il problema è risolto. Ora riesco a visualizzare la schermata
intera e ad avviare il processo.
Grazie, buona giornata.

Il ven 2 set 2022, 20:05 icomei ***@***.***> ha scritto:
